### ISSUE TITLE
keymap.bind() does work with keys like 'M-f1' and similar

### ISSUE THREAD

**Issue by Astronavigator** [mooffie/mc#2]
**keymap.bind**() function  does not work with a lot of key combinations like:
1. ALT+F1 (ALT+F2, ALT+F3, ...)
2. CTRL+F1 (CONTROL+F2, ...)

Does not depend on style of definition combination. For example, these combination work correctly

```
 M-x (alt+X)
 C-x f1 (CTRL+X, F1)
```

But these - does not (have no effect): 

```
  M-f1, C-f1, S-f1
```

Would be best to allow users to use characters codes (users can get them using **showkey** command or something similar):

```
[56]-[59] (ALT+F1)
```

**Comment by mooffie** [comment]
Hi!

> keymap.bind() function does not work with a lot of key combinations like:
> 1. ALT+F1 (ALT+F2, ALT+F3, ...)
> 2. CTRL+F1 (CONTROL+F2, ...)

That's because you first need to teach MC about these keys (mc^2 changes nothing in this subsystem of MC). Why aren't these special keys recognized automatically? Maybe the terminfo/termcap databases don't have entries for them.

Do "man mc" and look for "Terminal databases" for information, but I'll save you the bother:

To teach MC about a key it doesn't recognize, do as follows:

(1) First, make sure the terminal indeed receives this key. Run 'cat' and type the key to verify this.

(2) Open `/usr/share/mc/mc.lib` (or `~/.config/mc/ini`) in an editor and locate/create the "[terminal:xterm]" section (replace "xterm" by your $TERM). Then follow the example in `mc.lib`. For example, in my `mc.lib` I teach MC about M-f6/C-f6 this way:

```
[terminal:xterm]
...
alt-f6=\\e[17\;3~
ctrl-f6=\\e[17\;5~
```

Use the string you see in 'cat'. You represent ESC as "\e" **and semicolon as "\;"**.

**Don't use the two-letter prefixes "m-/c-/s-" in that file: these are just convenience shortcuts `keymap.bind()` provides.**

**Shift-functions are a special case (AFAIK).** Instead of "shift-f6" you use "f16" (that is, you add ten). I.e., do `keymap.bind('f16', whatever)` instead of `keymap.bind('s-f6', whatever)`. Your MC probably already knows about these keys so you don't need to teach it.

Note: I prefer to use `mc.lib` instead of `~/.config/mc/ini` (do "mc -F" to see the exact paths) because the latter might get overwritten if you have several instances of MC running.

Note: You'll usually use `ui.Panel.bind()` or `ui.Editbox.bind()` instead of `keyboard.bind()`, as they pass you the object of interest (panel, editor, etc) as argument

**Comment by Astronavigator** [comment]
Hi, Mooffie!

Thanks for such a complete instructions. I followed them, and now my mc² recognizes ALT+F1, ALT+F2 combinations.

Maybe it is good idea to include most common combinations (like alt-f1,...alt-f10, ctrl-f1,..,ctrl-f10, etc) to default ini file. 

Adding ability to use cat-like codes would be also useful (since I could share my lua-modules with friends, and it should work without changing ini files). Code will be a bit less understandable, but lua-code, which does not need changes in ini-files is much better than code that does need these changes.

```
ui.Panel.bind('\\eO3P', myfun) -- ALT+F1
(instead of)
ui.Panel.bind('alt-f1', myfun)  
```

**Comment by mooffie** [comment]
I neglected to explain why your original proposal wasn't a good one. It's better late than never:

> Would be best to allow users to use characters codes (users can get them using showkey command or something similar):
> [...]
> Adding ability to use cat-like codes would be also useful (since I could share my lua-modules with friends, and it should work without changing ini files). 
> 
> ```
> ui.Panel.bind('\\eO3P', myfun) -- ALT+F1
> (instead of)
> ui.Panel.bind('alt-f1', myfun)  
> ```

The problem is that these "escape sequences" aren't portable: there are differences between the terminals: XTerm, Konsole, the Linux console, the FreeBSD console, etc. Each sends different sequences for such keys. So if you embed such sequence directly in your source code it will work on your own system only, not on everybody's systems.

> Maybe it is good idea to include most common combinations (like alt-f1,...alt-f10, ctrl-f1,..,ctrl-f10, etc) to default ini file.

MC's maintainers will have to maintain a database of the various terminals and the sequences they send. This is not practical.

But there's a bigger problem with the "fancy" keys you're interested in: these keys are typically already used by the environment. E.g., ALT-F1 is used in the linux console to switch to the first VT console. Alt-F2 is used in many window managers for the "Run..." command. On my system I use Ctrl-F1 till Ctrl-F5 to launch the media player. So it's not a good idea to pick these keys as defaults for your module. 

It's better to be conservative and follow the way the modules in mc^2 do it:
- Your module should expose functions. The user himself then picks the keys, e.g., by doing `keymap.bind('whatever-i-want', astro.do_something)` in his user Lua folder.
- You can provide your own default keybindings, like "C-x a d", "C-x a z", ... the "C-x a" is the prefix for your module ("a" because, for example, you call it "astro"). Using prefixes is relatively safe because then you're less liable to clash with another programmer's module's. You can provide these bindings in a separate file so a user can easily copy it into his Lua folder and modify it.

**Comment by Astronavigator** [comment]
Hi, moofie! 
Thanks a lot for your explanation.
Sorry to bother you again, but there is one thing I want to notice. 

I don't think actually that midnight commander uses _conservative_ key combinations. Actually all those combinations like **C-x a b c d** are really fancy, and when I use mc I really miss real conservative combinations like **ALT+F1**, **ALT+F2**, **CTR+L**, etc (which are always short and handy).

These key combinations are _absolutely standard for all Norton Commander-like file managers_. All commanders that I have ever used, support these combinations: 
1. Norton Commander
2. Volkov Commander
3. Far manager
4. Total commander
5.  Wal commander

These combinations are absolutely standard for all commanders, and only midnight commander prefers to use his own "conservative" (which are not) key combinations. And except mc there are no popular file manager that uses key combinations like **C-x i** instead of **C-l** (or some **C-x a b c d** instead of **C-F[n]**). And there is very simple reason why: _key combinations like **C-x a b c d** are not handy, but combinations like **C-F1** are_.

Most of those commanders worked in **DOS** or **MS-Windows**, but **Wal commander** supports standard combinations even in linux, so I don't think that OS really matters here. (Actually Wal commander has its own console emulator, but it does not really matter).

So, for me and most users that started to use mc after NC, VC, FAR, etc, it is mc uses "fancy" key combinations, but all other commanders use "conservative". And a lot of users miss real conservative key combinations.

The first thing I've made after installing mc² was new conservative-like drive selection box, binded to  **ALT+F1**, **ALT+F2** (with auto-mounting). The second thing I planned to do was conservative information panel, binded to **CTRL+L** (instead of very unhandy and buggy **C-x i** info panel), but seems like it is impossible to realize using lua code yet. 

So, I am not looking for "fanciness". **For me "conservatism" is the _most desired_ and missing thing in mc.**

I can understand, that there can be some technical difficulties (but solvable) to realize supporting of conservative key combinations on different console emulators. But to be honest we must accept that these difficulties are not because of some sort of "fanciness". It is just technical difficulties, nothing more.

P.S. Sorry for my English. My native language is Russian.

**Comment by mooffie** [comment]
> Sorry to bother you again, 

You're not bothering; on the contrary.

> The second thing I planned to do was conservative information panel, 
> binded to CTRL+L (instead of very unhandy and buggy C-x i info panel),
> but seems like it is impossible to realize using lua code yet.

You can use the 'docker' module to inject a multi-line label widget to the filemanager dialog and show there whatever you want (there's a screenshot showing RSS feed displayed there). I'll write an example when I have the time. Or just display whatever you want in a popup.

(BTW, **were you implying that you can't override CTRL+L from Lua? If you did then this is certainly not true.**)

BTW, several people have asked to add various extra information to the "quick info" pane and I was planning to suggest a feature (to mc, not just to mc^2): to have "quick info" also display the output of a user script.

> there are no popular file manager that uses key combinations like C-x i instead of C-l 

That's because there's a tradition in the Unix world to make C-l in the terminal refresh the screen. That's what mc uses this key for (by default). You can very easily bind C-l to the "quick info" command instead (in plain mc too, not just in mc^2).

> Most of those commanders worked in DOS or MS-Windows, but Wal commander supports standard combinations even in linux, so I don't think that OS really matters here.

The OS **does matter**. It's **all** that matters, actually.

Wal commander, judging by its screenshots, is a GUI app. It's an X11 app, not a **terminal** app. X11 apps have no limitation with the keyboard.

The problem with mc is that it's a terminal app. So it has limitations with the keyboard, limitations that have to do with the history of Unix.

In the Unix world (which includes Linux, FreeBSD, Mac OSX, etc.), terminals send the app a string of characters on a key press. Depending on the terminal type, the terminal may not respond to all keys, and different terminals don't send the same string for a certain key. That's why a unix system comes with a database that describes the details of each terminal type. But this database, as evident, doesn't describe **all** the keys, and here's the problem.

> I really miss real conservative combinations like ALT+F1, ALT+F2, CTR+L, etc (which are always short and handy).

But you already solved your problem, didn't you? I explained to you the general way to teach mc to recognize a certain key.

Instead of investing time in rants, you should have invested in other venues, such as:
- Creating a snippet (of the .ini file) that teaches mc about all the ALT-Fn and Ctrl-Fn combinations and uploading it to mc's wiki.
- Approaching mc's maintainers (or me) with the proposal to ship it with mc (or mc^2).
- Doing some investigative work to find out why curses/termcap/terminfo don't contain this information already and whether theoretically it can contain it (because we'd be interested in knowing such historical trivia facts).

> I really miss real conservative combinations like ALT+F1, ALT+F2, [...]

No problem: use them. MC itself won't ever ship with bindings for ALT-Fn and Ctrl-Fn **by default**. That's because these keys combinations **aren't always available**: ALT-Fn does **not** work in the Linux console (it's used to switch virtual screens), and in GUI desktops these keys are **used** anyway (e.g., ALT-F2 runs command, ALT-F4 closes windows, etc.). As for Ctrl-Fn: I see they too aren't recognized in the linux console. And neither in 'tmux'... 

While this may give you the impression that unix (or "posix") is limited, it's a rather wrong impression (I don't have the time right now to explain why).

**Comment by Astronavigator** [comment]
> You're not bothering; on the contrary.

Glad to hear that.

> (BTW, were you implying that you can't override CTRL+L from Lua? If you did then this is certainly not true.)

Seems like you understood me wrong here. I did not mean, that I cannot use "CTRL+L" combination. I mean, that info panel is not accessible from lua code. Or maybe you already fixed it? 
I tried a month ago, but did not find any example or information on the site (and samples folder) how to change information panel, or make new information panel. That is why I've made a conclusion that it is not possible from lua code yet. (There was example of custom file system, but it is not the same).

I even tried to use ui.panel's "draw"  event, but it does not work for information panel.

> But you already solved your problem, didn't you? I explained to you the general way to teach mc to recognize a certain key.

Not yet. I've solved problem of missing drive selection dialog, but there are still a lot of work to make my mc more conservative. The problem is not only about keys, it is also about behavior.

> BTW, several people have asked to add various extra information to the "quick info" pane and I was planning to suggest a feature (to mc, not just to mc^2): to have "quick info" also display the output of a user script.

I think it would be best to fully rewrite info panel. Probably mc should run some lua script to draw information panel. By default this script can have same behavior that standard mc's info panel (maybe not, because standard info panel is pretty ugly), but users can change it to fit their needs. Surely, users will be glad to have this ability.

> The problem with mc is that it's a terminal app. So it has limitations with the keyboard, limitations that have to do with the history of Unix.

I don't think that problem is that mc is terminal app. What is actually terminal app? It is just application that uses console for output. It has no limitation to use any other functions. It can use any device like keyboard and mouse. Terminal application can even have X11 windows if it likes (so it will be probably mixed console and graphical application). 
But there is another problem. Developers want mc to work through remote terminals (by SSH, etc.) and this requirement adds some limitations. With this limitation mc cannot use keyboard directly, it must use terminal functions instead.

Maybe you familiar with far manager (most popular nc-like file manager for windows). One of its plugins even can show preview of images on its panel, even if far manager is console application. Far manager (with some plugins)  also can play sounds, play videos, can show graphical context menu  (by right click), and there are more many-many very useful but not console possibilities that are available in Far (some of these functions are standard, some need additional plugins). And yet, Far manager is console application.

So there are two ways of developing terminal (console) applications: with restrictions that will make them possible to use it remotely (from SSH), and without. Both have its own benefits. I don't insist that one way is better than another and also, maybe mc already made its choice and there is no need to change it. I just noticed that second way is also exists.
