### ISSUE TITLE
at start of mc

### ISSUE THREAD

**Issue by questor** [mooffie/mc#4]
I've used latest github-sources and compiled my own binary, but when I start the executable every time I get a warning "User supplied format looks invalid, reverting to default." and I get the new "Welcome" dialog where I can select what options I want to have enabled... is that a known bug or where should I look what's going on?

**Comment by questor** [comment]
I've found out what is going on and that I really need to setup my own lua configuration, but I think for the average user (not willing to read through all the lua stuff) it's not clear how to use this really great variant of mc. when correctly configured it's a really great working enhancement, but the first setup is not (or at least was not to me) self-explanatory.

**Comment by mooffie** [comment]
Hi!

I'm aware of this issue. It's not a bug. The problem is as follows:

When you tick certain radio boxes in the "Welcome" screen (which is part of the "demo" module), some fields are added to your custom format string. Namely "gitstatus" and/or "mp_duration". Now, if you save MC's setup and restart MC (or if you restart Lua, with C-l), MC will complain ("User supplied format looks invalid, reverting to default") because the Lua modules that implement these two fields aren't loaded. These modules are only loaded later: if you select them again in the "Welcome" screen...

(BTW, the error is displayed twice: once for each panel. This is why you need to press ENTER twice.)

Unfortunately, I don't see a solution to this usability problem. It's certainly a bummer. Ideally MC should print a more useful error message (e.g., "the field 'gitstatus' in your format string isn't known").

> I've found out what is going on and that I really need to setup my own lua configuration,

Here's a tip:

Use the Snapshots feature (Alt-PgDn) to save just the "custom_format" property (i.e., once your panels are showing a Git or Mplayer fields you like). Then you can restore it very easily if it goes away. (The Snapshot dialog has a Help screen: see the section "The state" there.)

> but I think for the average user (not willing to read through all the lua stuff)

Yeah. Even the non-average user doesn't have time to "read through all the lua stuff". Myself included! I need to make it possible to call up the "Welcome" screen(s) even if the user has set up his own Lua configuration. E.g., by typing ":demo". Or maybe I need to think of something more extensive, like some mechanism that exposes the features in menus.
