### ISSUE TITLE
how could i make a plugin to copy with external command

### ISSUE THREAD

**Issue by osatien** [mooffie/mc#7]
that is .. i want to make a plugin that lists files ( this is ok ) from remote (i will do rclone ls remote: parse and present that) stat over file can be done, but i dont want to copy with mc ... i want to call external command when i hit f5 or ESC-5 that makes the external copy outside/in background from mc. i want to log the status line of the external copy into "main window". 

This are my intentions. But i dont know how can i hook f5/copy command, will f5 only be hooked when i am in my remote, or it will be "forever"? so i must know when it is done to/from myremote and when it is not ....

**Comment by mooffie** [comment]
Hi!

Here's a snippet that makes F5 launch your custom copy command:

https://gist.github.com/mooffie/d8c13c62e3638d916627619c30ab37a7

Also check the following snippet, which does something similar for F8:

https://gist.github.com/mooffie/4111a39e18934e2b4e7001c1c0cd3213

(Note that this F8 snippet lets you choose between `os.execute` and `mc.execute`.)

The F8 snippet also shows how to create a temporary file. You can put your command(s) in it -- this solves nasty quoting issues.

> 
> i want to log the status line of the external copy into "main window".

If you want to see result of `mc.execute`, simply hit Ctrl-O.

>
> makes the external copy outside/in background from mc

Oh, you want to continue working inside MC while the copying is going on. So instead of launching "cp" directly, lauch "xterm -e SOME_COMMAND &" or whatever (doing this with `os.execute` is fine). And note the comment above about how to solve quoting issues.

**Comment by mooffie** [comment]
>
> when i hit f5 or ESC-5

Other key ideas:

    ui.Panel.bind('f15', function(pnl)
      alert('you hit shift f5')
      -- Note: if your terminal is misconfigured, this won't work.
    end)

    ui.Panel.bind('C-x f5', function(pnl)
      alert('you hit C-x, then f5')
      -- You're not limited to C-x. You can use any key sequence, in any length.
    end)

**Comment by osatien** [comment]
the problem was how to hook to copy and have src and target in params.

now its clearer many thank you

**Comment by mooffie** [comment]
> 
> so i must know when it is done to/from myremote and when it is not ....

Tip: in your F5 handler do:

    devel.view( pnl.vdir:extract() )

this will show you what MC knows about the path. Note the `vfs_prefix` field.

The reference:

   https://www.geek.co.il/~mooffie/mc-lua/docs/html/classes/fs.VPath.html

**Comment by osatien** [comment]
I have read that but I haven't read anything about hooking and src and target in copy command
